const config = {
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYjMzNzU3OWMxMDIxYTg3MmVlZGRjOCIsInJvbGUiOlsicmVhZC1hbGwiLCJyZWFkLXBvc3RzIl0sImlhdCI6MTYzOTEzNTc2NywiZXhwIjoxNjM5MTM1ODUzfQ.7bjON22eg9ySkwdz2pw_355EQjUVOF5IZnzLwCQm34I"
}

export default config;