const config = {
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYjMzNzU3OWMxMDIxYTg3MmVlZGRjOCIsInJvbGUiOlsicmVhZC1hbGwiLCJyZWFkLXBvc3RzIl0sImlhdCI6MTYzOTEzNTI1OSwiZXhwIjoxNjM5MTM1MzQ1fQ.n9fcOgdxTgzmqslYGhZPcd8tAiCPer_hUvJ3THh7WmM"
}

export default config;