const config = {
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYjM3M2IyYzBhYmJiMTUxMmRkOWU1NyIsInJvbGUiOlsicmVhZC1hbGwiLCJyZWFkLXBvc3RzIiwibWFuYWdlLXBvc3RzIl0sImlhdCI6MTYzOTE1MDUyMCwiZXhwIjoxNjM5MjM2OTIwfQ.jMbyc-IunYOmXz1rkCWMKGI1m-NX9LQgYFrrcDXgH6o"
}

export default config;